# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uH25YEMDlfLFzjTWyGeAxBOtnscGLSDk
"""

# SALVE ESSE CÓDIGO COMO app.py E RODE: streamlit run app.py
# ─────────────────────────────────────────────────────────────

streamlit_code = '''
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, roc_auc_score, recall_score
from imblearn.over_sampling import SMOTE

st.set_page_config(page_title="Fraude em Cartões", page_icon="💳", layout="wide")
st.title("💳 Detecção de Fraude em Cartões de Crédito")
st.markdown("Liga de Data Science — Mini Projeto")

# ── Carrega e processa os dados ─────────────────────────────────────────────
@st.cache_data
def carregar_dados():
    df = pd.read_csv("creditcard.csv")
    df = df.drop_duplicates().reset_index(drop=True)
    scaler = StandardScaler()
    df["Amount_scaled"] = scaler.fit_transform(df[["Amount"]])
    df["Time_scaled"]   = scaler.fit_transform(df[["Time"]])
    df = df.drop(["Amount", "Time"], axis=1)
    return df

@st.cache_resource
def treinar_modelo(df):
    X = df.drop("Class", axis=1)
    y = df["Class"]
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y)
    smote = SMOTE(random_state=42)
    X_train_bal, y_train_bal = smote.fit_resample(X_train, y_train)
    rf = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
    rf.fit(X_train_bal, y_train_bal)
    return rf, X_test, y_test

df = carregar_dados()
rf, X_test, y_test = treinar_modelo(df)

# ── Abas ─────────────────────────────────────────────────────────────────────
aba1, aba2, aba3 = st.tabs(["📊 Visão Geral", "📈 Análise", "🤖 Modelo"])

with aba1:
    col1, col2, col3 = st.columns(3)
    col1.metric("Total de Transações", f"{len(df):,}")
    col2.metric("Fraudes",             f"{df['Class'].sum():,}")
    col3.metric("Taxa de Fraude",      f"{df['Class'].mean()*100:.3f}%")

    fig, ax = plt.subplots(figsize=(6, 3))
    contagem = df["Class"].value_counts()
    ax.bar(["Legítima", "Fraude"], contagem.values,
           color=["#2563EB", "#DC2626"], edgecolor="white")
    ax.set_title("Distribuição do Alvo")
    st.pyplot(fig)

with aba2:
    st.subheader("Valor das Transações ao Longo do Tempo")
    # recupera Amount original para análise
    df_orig = pd.read_csv("creditcard.csv")
    legitimas = df_orig[df_orig["Class"] == 0].sample(3000, random_state=42)
    fraudes   = df_orig[df_orig["Class"] == 1]
    fig2, ax2 = plt.subplots(figsize=(10, 4))
    ax2.scatter(legitimas["Time"], legitimas["Amount"],
                alpha=0.3, s=5, color="#2563EB", label="Legítima")
    ax2.scatter(fraudes["Time"],   fraudes["Amount"],
                alpha=0.8, s=15, color="#DC2626", label="Fraude")
    ax2.set_xlabel("Tempo (s)"); ax2.set_ylabel("Valor (€)")
    ax2.legend(); st.pyplot(fig2)

with aba3:
    threshold = st.slider("Limiar de decisão", 0.1, 0.9, 0.5, 0.01)
    y_proba   = rf.predict_proba(X_test)[:, 1]
    y_pred    = (y_proba >= threshold).astype(int)

    col1, col2 = st.columns(2)
    col1.metric("Recall",   f"{recall_score(y_test, y_pred):.2%}")
    col2.metric("AUC-ROC",  f"{roc_auc_score(y_test, y_proba):.4f}")
    col1.metric("Fraudes detectadas", int(recall_score(y_test,y_pred)*y_test.sum()))
    col2.metric("Fraudes perdidas",   y_test.sum()-int(recall_score(y_test,y_pred)*y_test.sum()))
    st.text(classification_report(y_test, y_pred,
            target_names=["Legítima","Fraude"]))
'''

print("Cole o código acima em um arquivo app.py")
print("Depois instale o streamlit: pip install streamlit")
print("E rode no terminal: streamlit run app.py")